services:
  trello-server:
    container_name: trello-server
    image: nhphuc414/trello-app/trello-server:latest
    ports:
      - '8017:8017'
    restart: always
  trello-client:
    container_name: trello-client
    image: nhphuc414/trello-app/trello-client:latest
    depends_on:
      - trello-server
    ports:
      - '4173:80'
    restart: always
