services:
  trello-server:
    container_name: trello-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8017:8017'
    env_file:
      - ./server/.env
    restart: always
  trello-client:
    container_name: trello-client
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - trello-server
    ports:
      - '4173:80'
    restart: always
